name: Post Photo to Instagram

on:
  schedule:
    - cron: '0 10 * * *' # every day at 10:00 UTC
  workflow_dispatch: # allow manual run

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for session file
        run: ls -l automation/igSession.json || echo "Session file not found"

      - name: Restore Instagram session cache
        uses: actions/cache@v3
        with:
          path: automation/igSession.json
          key: ig-session

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Post image
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          PHOTO_BASE_URL: ${{ secrets.PHOTO_BASE_URL }}
        run: node automation/postImage.js

      - name: Save Instagram session cache
        uses: actions/cache/save@v3
        with:
          path: automation/igSession.json
          key: ig-session

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit usedImages.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add automation/usedImages.json
          git commit -m "Update used images list [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}